### ISSUE TITLE
web配置wifi的功能

### ISSUE THREAD

**Issue by chenguo2000** [a2633063/zClock_Matrix#1]
你好，我看功能介绍里写了实现web配置wifi。但是首次使用又有APP，我想问一下web配置wifi是否首次也可用，而无需使用app。

**Comment by a2633063** [comment]
是的


刷机时erase一样  然后刷入
开机后显示 AP Web  
这时连接热点,然后进入网页192.168.0.1配网
完成后确认设备连上 时间就能显示了


如果没erase可能开机后显示wifi   之后显示OK表示连接wifi成功  显示err表示连接失败 之后显示AP? 这时按下flash那个按键就进入web配网了 按上面操作就好  


以上为简单文档说明  后续完成使用说明文档

**Comment by a2633063** [comment]
app更新了  增加了此设备,但由于功能暂时不多所以我暂时没有正式发布出来
可以在  https://github.com/a2633063/SmartControl_Android_MQTT/blob/master/app/release/app-release.apk   下载安装
详细的说明文档后续更新,可以按照其他设备尝试操作
后续再正式发布此版本的app端
当前支持功能: ota升级/设置亮度/设置显示方向/推送滚动显示内容

当前已经可以用此app更新固件,修复了部分显示滚动文本的bug.固件更新详细内容见release
